In [1]:

import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter



# Read the clean_flavors_of_cacao.csv

In [2]:
# Load the data
file_path = Path('clean_flavors_of_cacao.csv')
df = pd.read_csv(file_path)
df.head()


Company Bean_Origin_or_Bar_Name   REF  Review_Date  Cocoa_Percent  \
0  A. Morin             Agua Grande  1876         2016           63.0   
1  A. Morin                   Kpime  1676         2015           70.0   
2  A. Morin                  Atsane  1676         2015           70.0   
3  A. Morin                   Akata  1680         2015           70.0   
4  A. Morin                  Quilla  1704         2015           70.0   

  Company_Location  Rating Bean_Type    Broad_Bean_Origin Ingredients  \
0           France    3.75   missing  Sao Tome & Principe  4- B,S,C,L   
1           France    2.75   missing                 Togo  4- B,S,C,L   
2           France    3.00   missing                 Togo  4- B,S,C,L   
3           France    3.50   missing                 Togo  4- B,S,C,L   
4           France    3.50   missing                 Peru  4- B,S,C,L   

   Most_Memorable_Characteristics country_code  latitude  longitude  \
0      sweet, chocolatey, vegetal           ST  0.186360   6.613081   
1       burnt wood, earthy, choco           TG  8.619543   0.824782   
2           roasty, acidic, nutty           TG  8.619543   0.824782   
3  mild profile, chocolaty, spice           TG  8.619543   0.824782   
4    grainy texture, cocoa, sweet           PE -9.189967 -75.015152   

       continent  
0         Africa  
1         Africa  
2         Africa  
3         Africa  
4  South America

In [3]:
df= df.drop(columns=["Company","REF","Bean_Origin_or_Bar_Name","Most_Memorable_Characteristics","continent"], axis=1)
df.head()

Review_Date  Cocoa_Percent Company_Location  Rating Bean_Type  \
0         2016           63.0           France    3.75   missing   
1         2015           70.0           France    2.75   missing   
2         2015           70.0           France    3.00   missing   
3         2015           70.0           France    3.50   missing   
4         2015           70.0           France    3.50   missing   

     Broad_Bean_Origin Ingredients country_code  latitude  longitude  
0  Sao Tome & Principe  4- B,S,C,L           ST  0.186360   6.613081  
1                 Togo  4- B,S,C,L           TG  8.619543   0.824782  
2                 Togo  4- B,S,C,L           TG  8.619543   0.824782  
3                 Togo  4- B,S,C,L           TG  8.619543   0.824782  
4                 Peru  4- B,S,C,L           PE -9.189967 -75.015152

In [4]:
df['Rating'].describe()


count    1960.000000
mean        3.175383
std         0.478560
min         1.000000
25%         2.750000
50%         3.250000
75%         3.500000
max         5.000000
Name: Rating, dtype: float64

In [5]:
def bin_ratings(rating):
    if rating >= 4.0: 
        return 'Premium_Elite'
    elif  rating >= 3.0 and rating < 4.0: 
        return 'Satisfactory'
    elif  rating >= 2.0 and rating < 3.0:
        return 'Unsatisfactory'
    else:
        return "unpleasant"



In [6]:
df['Rating'] = df['Rating'].apply(bin_ratings)

# Split the Data into Training and Testing


In [7]:
y = df["Rating"]
X = df.drop(columns="Rating")
X = pd.get_dummies(X)
X

Review_Date  Cocoa_Percent   latitude  longitude  \
0            2016           63.0   0.186360   6.613081   
1            2015           70.0   8.619543   0.824782   
2            2015           70.0   8.619543   0.824782   
3            2015           70.0   8.619543   0.824782   
4            2015           70.0  -9.189967 -75.015152   
...           ...            ...        ...        ...   
1955         2011           70.0  -9.189967 -75.015152   
1956         2011           65.0  -0.228021  15.827659   
1957         2011           65.0  20.593684  78.962880   
1958         2011           62.0  20.593684  78.962880   
1959         2010           65.0 -14.235004 -51.925280   

      Company_Location_Argentina  Company_Location_Australia  \
0                              0                           0   
1                              0                           0   
2                              0                           0   
3                              0                           0   
4                              0                           0   
...                          ...                         ...   
1955                           0                           0   
1956                           0                           0   
1957                           0                           0   
1958                           0                           0   
1959                           0                           0   

      Company_Location_Austria  Company_Location_Belgium  \
0                            0                         0   
1                            0                         0   
2                            0                         0   
3                            0                         0   
4                            0                         0   
...                        ...                       ...   
1955                         1                         0   
1956                         1                         0   
1957                         1                         0   
1958                         1                         0   
1959                         1                         0   

      Company_Location_Bolivia  Company_Location_Brazil  ...  country_code_TG  \
0                            0                        0  ...                0   
1                            0                        0  ...                1   
2                            0                        0  ...                1   
3                            0                        0  ...                1   
4                            0                        0  ...                0   
...                        ...                      ...  ...              ...   
1955                         0                        0  ...                0   
1956                         0                        0  ...                0   
1957                         0                        0  ...                0   
1958                         0                        0  ...                0   
1959                         0                        0  ...                0   

      country_code_TT  country_code_TZ  country_code_UG  country_code_US  \
0                   0                0                0                0   
1                   0                0                0                0   
2                   0                0                0                0   
3                   0                0                0                0   
4                   0                0                0                0   
...               ...              ...              ...              ...   
1955                0                0                0                0   
1956                0                0                0                0   
1957                0                0                0                0   
1958                0                0                0                0   
1959      

In [8]:
X.describe()

Review_Date  Cocoa_Percent     latitude    longitude  \
count  1960.000000    1960.000000  1960.000000  1960.000000   
mean   2012.264796      71.760204     2.287706   -38.732759   
std       2.918282       6.657419    13.001691    63.416232   
min    2006.000000      42.000000   -25.274398  -172.104629   
25%    2010.000000      70.000000    -9.189967   -78.183406   
50%    2013.000000      70.000000     1.373333   -66.589730   
75%    2015.000000      75.000000    12.865416     0.000000   
max    2017.000000     100.000000    37.090240   179.414413   

       Company_Location_Argentina  Company_Location_Australia  \
count                 1960.000000                 1960.000000   
mean                     0.004592                    0.025510   
std                      0.067625                    0.157709   
min                      0.000000                    0.000000   
25%                      0.000000                    0.000000   
50%                      0.000000                    0.000000   
75%                      0.000000                    0.000000   
max                      1.000000                    1.000000   

       Company_Location_Austria  Company_Location_Belgium  \
count               1960.000000               1960.000000   
mean                   0.014286                  0.020918   
std                    0.118696                  0.143148   
min                    0.000000                  0.000000   
25%                    0.000000                  0.000000   
50%                    0.000000                  0.000000   
75%                    0.000000                  0.000000   
max                    1.000000                  1.000000   

       Company_Location_Bolivia  Company_Location_Brazil  ...  \
count               1960.000000              1960.000000  ...   
mean                   0.001020                 0.017857  ...   
std                    0.031936                 0.132466  ...   
min                    0.000000                 0.000000  ...   
25%                    0.000000                 0.000000  ...   
50%                    0.000000                 0.000000  ...   
75%                    0.000000                 0.000000  ...   
max                    1.000000                 1.000000  ...   

       country_code_TG  country_code_TT  country_code_TZ  country_code_UG  \
count      1960.000000      1960.000000      1960.000000      1960.000000   
mean          0.001531         0.019898         0.018367         0.003571   
std           0.039103         0.139685         0.134310         0.059670   
min           0.000000         0.000000         0.000000         0.000000   
25%           0.000000         0.000000         0.000000         0.000000   
50%           0.000000         0.000000         0.000000         0.000000   
75%           0.000000         0.000000         0.000000         0.000000   
max           1.000000         1.000000         1.000000         1.000000   

       country_code_US  country_code_VE  country_code_VN  country_code_VU  \
count      1960.000000      1960.000000      1960.000000      1960.000000   
mean          0.014286         0.119388         0.020408         0.003571   
std           0.118696         0.324327         0.141428         0.059670   
min           0.000000         0.000000         0.000000         0.000000   
25%           0.000000         0.000000         0.000000         0.000000   
50%           0.000000         0.000000         0.000000         0.000000   
75%           0.000000         0.000000         0.000000         0.000000   
max           1.000000         1.000000         1.000000         1.000000   

       country_code_WS  country_code_ZZ  
count      1960.000000      1960.000000  
mean          0.002041         0.052041  
std           0.045141         0.222166  
min           0.000000         0.000000  
25%           0.000000         0.000000  
50%           0.000000         0.000000  
75%           0.000000         0.00

In [9]:
# Check the balance of our target values
y.value_counts()

Satisfactory      1353
Unsatisfactory     484
Premium_Elite      105
unpleasant          18
Name: Rating, dtype: int64

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,
   y,test_size= 0.4,train_size=0.6 , random_state=1, stratify=y)

In [11]:

Counter(y_train)

Counter({'Satisfactory': 812,
         'Unsatisfactory': 290,
         'Premium_Elite': 63,
         'unpleasant': 11})

In [12]:
from sklearn.preprocessing import StandardScaler

# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

# Oversampling

In [13]:
#Naive Random Oversampling

# Resample the training data with the RandomOversampler
from imblearn.over_sampling import RandomOverSampler
# Instantiate the model
ros = RandomOverSampler(random_state=1)
# Resample the targets
X_resampled, y_resampled = ros.fit_resample(X_train_scaled, y_train)
Counter(y_resampled)



Counter({'Satisfactory': 812,
         'Unsatisfactory': 812,
         'Premium_Elite': 812,
         'unpleasant': 812})

## LogisticRegression

In [14]:
# from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)
# Calculate predictions
y_pred = model.predict(X_test_scaled)


C:\Users\Tata\anaconda3\envs\mlenv\lib\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [15]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
balanced_accuracy_score(y_test, y_pred)

0.48007868753385835

In [16]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

# Create a DataFrame from the confusion matrix.
print(cm)

[[ 21  14   6   1]
 [144 225 164   8]
 [ 38  68  84   4]
 [  1   1   1   4]]


In [17]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

                      pre       rec       spe        f1       geo       iba       sup

 Premium_Elite       0.10      0.50      0.75      0.17      0.61      0.37        42
  Satisfactory       0.73      0.42      0.66      0.53      0.52      0.27       541
Unsatisfactory       0.33      0.43      0.71      0.37      0.55      0.30       194
    unpleasant       0.24      0.57      0.98      0.33      0.75      0.54         7

   avg / total       0.59      0.43      0.68      0.47      0.54      0.28       784



# SMOTE Oversampling


In [18]:


# Resample the training data with SMOTE
from imblearn.over_sampling import SMOTE
X_resampled, y_resampled = SMOTE(random_state=1,sampling_strategy='auto').fit_resample(X_train_scaled, y_train)

Counter(y_resampled)



Counter({'Satisfactory': 812,
         'Unsatisfactory': 812,
         'Premium_Elite': 812,
         'unpleasant': 812})

In [19]:
# Train the Logistic Regression model using the resampled data
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

C:\Users\Tata\anaconda3\envs\mlenv\lib\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(random_state=1)

In [20]:
# Calculated the balanced accuracy score
y_pred = model.predict(X_test_scaled)
balanced_accuracy_score(y_test, y_pred)

0.4202880944667823

In [21]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[ 17,  18,   6,   1],
       [123, 230, 179,   9],
       [ 39,  71,  82,   2],
       [  0,   2,   2,   3]], dtype=int64)

In [22]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                      pre       rec       spe        f1       geo       iba       sup

 Premium_Elite       0.09      0.40      0.78      0.15      0.56      0.30        42
  Satisfactory       0.72      0.43      0.63      0.53      0.52      0.26       541
Unsatisfactory       0.30      0.42      0.68      0.35      0.54      0.28       194
    unpleasant       0.20      0.43      0.98      0.27      0.65      0.40         7

   avg / total       0.58      0.42      0.65      0.47      0.52      0.27       784



# Undersampling

In [23]:
# Resample the data using the ClusterCentroids resampler

from imblearn.under_sampling import ClusterCentroids
# Instantiate
cc = ClusterCentroids(random_state=1)
X_resampled, y_resampled = cc.fit_resample(X_train, y_train)
Counter(y_resampled)

Counter({'Premium_Elite': 11,
         'Satisfactory': 11,
         'Unsatisfactory': 11,
         'unpleasant': 11})

In [24]:
# Train the Logistic Regression model using the resampled data
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

C:\Users\Tata\anaconda3\envs\mlenv\lib\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(random_state=1)

In [25]:
# Calculated the balanced accuracy score
y_pred = model.predict(X_test_scaled)
balanced_accuracy_score(y_test, y_pred)

0.3213855820735978

In [26]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

# Create a DataFrame from the confusion matrix.
print(cm)

[[ 20   4   5  13]
 [268  59  45 169]
 [ 63  19  25  87]
 [  1   1   1   4]]


In [27]:


# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))



                      pre       rec       spe        f1       geo       iba       sup

 Premium_Elite       0.06      0.48      0.55      0.10      0.51      0.26        42
  Satisfactory       0.71      0.11      0.90      0.19      0.31      0.09       541
Unsatisfactory       0.33      0.13      0.91      0.19      0.34      0.11       194
    unpleasant       0.01      0.57      0.65      0.03      0.61      0.37         7

   avg / total       0.58      0.14      0.88      0.18      0.33      0.11       784



# Combination (Over and Under) Sampling 

In [28]:
# Resample the training data with SMOTEENN
# Warning: This is a large dataset, and this step may take some time to complete
from imblearn.combine import SMOTEENN
smote_enn = SMOTEENN(random_state=1)
X_resampled, y_resampled = smote_enn.fit_resample(X, y)
Counter(y_resampled)

Counter({'Premium_Elite': 1234,
         'Satisfactory': 432,
         'Unsatisfactory': 827,
         'unpleasant': 1345})

In [29]:
# Train the Logistic Regression model using the resampled data
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

C:\Users\Tata\anaconda3\envs\mlenv\lib\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(random_state=1)

In [30]:
# Calculated the balanced accuracy score
y_pred = model.predict(X_test_scaled)
balanced_accuracy_score(y_test, y_pred)

0.38198219718933557

In [31]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix


cm = confusion_matrix(y_test, y_pred)

# Create a DataFrame from the confusion matrix.
print(cm)

[[ 20   6   4  12]
 [220 124  37 160]
 [ 56  34  21  83]
 [  2   0   0   5]]


In [32]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                      pre       rec       spe        f1       geo       iba       sup

 Premium_Elite       0.07      0.48      0.63      0.12      0.55      0.29        42
  Satisfactory       0.76      0.23      0.84      0.35      0.44      0.18       541
Unsatisfactory       0.34      0.11      0.93      0.16      0.32      0.09       194
    unpleasant       0.02      0.71      0.67      0.04      0.69      0.48         7

   avg / total       0.61      0.22      0.85      0.29      0.42      0.17       784

